### ISSUE TITLE
ios build error

### ISSUE THREAD

**Issue by justwezzz** [charleyw/cordova-plugin-alipay#1]
hi,charleyw.
I use the plugin into my project , when i `ionic build ios`,ionic throw an error.
`The following build commands failed:
    CompileC build/aliPayDemo.build/Debug-iphonesimulator/aliPayDemo.build/Objects-normal/i386/AlipayPlugin.o aliPayDemo/Plugins/wang.imchao.plugin.alipay/AlipayPlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Workspace/AliPayPluginDemo/aliPayDemo/platforms/ios/cordova/build-debug.xcconfig,-project,aliPayDemo.xcodeproj,ARCHS=i386,-target,aliPayDemo,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Workspace/AliPayPluginDemo/aliPayDemo/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Workspace/AliPayPluginDemo/aliPayDemo/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Workspace/AliPayPluginDemo/aliPayDemo/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Workspace/AliPayPluginDemo/aliPayDemo/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)`
I try to `ionic platform remove ios` and `cordova plugin remove wang.imchao.plugin.alipay` then i re-add these , but still get the same error.
I'm new to ios can you help me to solve this problem?

**Comment by charleyw** [comment]
Did you try to add other plugins? I think it's because of your environment. 
I did  not meet this kind of problem. And I found the similar issue here: https://github.com/driftyco/ionic-cli/issues/282

**Comment by justwezzz** [comment]
Commented `AlipayPlugin.m`->`pluginInitialize`->`self.appScheme = @"juduoduo://test";`
It works for me.

**Comment by charleyw** [comment]
You can update to latest code, i already updated the code.

**Comment by justwezzz** [comment]
thx
