### ISSUE TITLE
android 下取消支付会直接关闭整个程序

### ISSUE THREAD

**Issue by mjbin** [charleyw/cordova-plugin-alipay#10]
你好，我成功调出了支付的界面，然后未作其他操作关闭支付宝的界面会直接关掉了整个app

**Comment by charleyw** [comment]
可能是我下午push了新的代码的原因，加了callback，因为手头没有android手机，只测试了iOS. 明天去看看android。

**Comment by mjbin** [comment]
![image](https://cloud.githubusercontent.com/assets/3965629/12031451/12d14a18-ae47-11e5-822b-add5e5a4037c.png)
我更新了一下你的插件，然后现在用的第一种方法安装，结果装不了。

**Comment by charleyw** [comment]
是的，因为我把 PRIAVTE_KEY加进去了。值是私钥的内容。这两天太忙 没时间更新文档。

**Comment by mjbin** [comment]
你好，更新了插件已解决问题，最近在做微信支付，忘了处理这边的，感谢回复
