### ISSUE TITLE
ios支付宝客户端操作完成后不回调原app

### ISSUE THREAD

**Issue by xzlihao** [charleyw/cordova-plugin-alipay#14]
如果手机没有装支付宝app，调用wap支付成功或取消支付后都能调callback函数。
如果打开手机支付宝app，支付成功或取消支付都不调callback函数，怎么解决？
急！

**Comment by charleyw** [comment]
看一下，info.plist里面有没有一个a开头的url scheme. 有的话应该就能正常返回

**Comment by charleyw** [comment]
检查了一下代码，确实有问题。之前我给URL Scheme前面加了一个字母a，但是代码里面有两个地方没修改。更新一下代码就好了。
