### ISSUE TITLE
ios调用时似乎没有把privatekey写入到文件系统里？

### ISSUE THREAD

**Issue by veilevil** [charleyw/cordova-plugin-alipay#16]
ios调用pay，报错
`rsa_private read error : private key is NULL`

**Comment by charleyw** [comment]
应该是安装的时候private key没有传进去。能检查一下你的cordova版本是多少吗？

```
cordova -v
```

如果是5.1.1以下的版本呢，你可以试试看按照[手动安装的步骤](https://github.com/charleyw/cordova-plugin-alipay#手动安装)试试看。
还有确保你的key是**PKCS**格式的，详见这里[关于密钥的说明](https://github.com/charleyw/cordova-plugin-alipay#关于私钥)

**Comment by veilevil** [comment]
我重新安装以后，它好了，谢谢 @charleyw
