### ISSUE TITLE
安卓版在模拟器里返回空的sign

### ISSUE THREAD

**Issue by veilevil** [charleyw/cordova-plugin-alipay#17]
在SignUtil的第20行：
`PrivateKey priKey = keyf.generatePrivate(priPKCS8);`
执行出错了，catch到错误是：

java.security.spec.InvalidKeySpecException: java.lang.RuntimeException: error:0D07209B:asn1 encoding routines:ASN1_get_object:too long

**Comment by charleyw** [comment]
我没有遇到过这个问题，所以没办法知道这是怎么回事。
看样子，貌似是key有问题。确保你的key是PKCS格式的。[关于私钥](https://github.com/charleyw/cordova-plugin-alipay#关于私钥)

**Comment by veilevil** [comment]
确认了是key的问题，key少了一部分 @charleyw
