### ISSUE TITLE
调用这个插件付款成功之后退款怎么操作呢？

### ISSUE THREAD

**Issue by hyitclj** [charleyw/cordova-plugin-alipay#18]
现在应用需要加入一个退款业务，怎么实现退款呢？？？

**Comment by charleyw** [comment]
退款好像需要调支付宝的API。你可能需要自己开发后台，接受应用的请求。
这里有支付宝的退款DEMO，翻到最下面: https://doc.open.alipay.com/doc2/detail?treeId=54&articleId=103419&docType=1

**Comment by hyitclj** [comment]
调用支付宝支付。。。iOS应用在AppStore上面被拒了，好像不允许使用支付宝支付，支付需要使用In-App Purchase，这个怎么绕过他呢？怎么办呢？因为我看到也有一些苹果应用可以使用支付宝支付啊，比如美团淘宝等

**Comment by charleyw** [comment]
主要还是看你买啥东西吧。

我们现在做的一个在线订餐的平台。用户支付订餐的款，用的就是这个插件。并且在AppStore的review预览图上我都贴了支付的图。并没有问题。

建议你检查一下需要使用IAP的规则，还有就是提交review的时候不要勾有IAP如果你没有IAP功能的话。

**Comment by hyitclj** [comment]
我的是虚拟商品，是不是虚拟的不让用呢？IAP没有勾选啊

**Comment by hyitclj** [comment]
https://developer.apple.com/app-store/review/guidelines/
看第11项

**Comment by charleyw** [comment]
之前我提交的时候也看过这个，还在知乎上查了，貌似 虚拟物品，电子商品都需要用IAP。我第一次提交的时候就有支付功能了，现在提交了4次了，没有一次说过支付这个问题的。
不过我们的支付买的是线下的服务。我估计是不是这个区别啊

**Comment by hyitclj** [comment]
有可能，谢谢啊
