### ISSUE TITLE
ios 支付成功以后返回app直接退出，没有执行到成功或者失败的回调

### ISSUE THREAD

**Issue by htzhanglong** [charleyw/cordova-plugin-alipay#22]
ios 支付成功以后返回app直接退出，没有执行到成功或者失败的回调，android一切正常，不知道是什么原因，还请管理指教

**Comment by charleyw** [comment]
有错误信息吗？
可以看看xcode里面有没有报错，APP直接退出的话，应该是有什么错。

**Comment by htzhanglong** [comment]
没有错误信息的 用的是ionic这个框架，android好好的。单独整了个模块也是支付成功 或者取消支付的时候返回就会退出app

管理有没有qq 或者微信联系方式 可以付费帮忙调试，也可以付费帮忙开发其他插件

**Comment by htzhanglong** [comment]
会不会和我用的cordova 6.0 有关系

**Comment by charleyw** [comment]
完了等我有时间，我试试看看cordova 6.0，今天有点忙

**Comment by htzhanglong** [comment]
非常感谢管理
