### ISSUE TITLE
ios 支付成功或者取消支付以后app闪退，管理您用的是哪个版本的cordova

### ISSUE THREAD

**Issue by it-ionic** [charleyw/cordova-plugin-alipay#24]
ios 支付成功或者取消支付以后app闪退，用的是cordova6.0 和楼上的效果是一样的

不知道管理用的哪个版本的cordova，

管理心情好，帮忙整一下，对管理来说就是分钟的事情

**Comment by charleyw** [comment]
不好意思，上周我娃出生了，一直没时间，今天测试了cordova 6.0 我这边一切正常

**Comment by htzhanglong** [comment]
恭喜恭喜     那我换个项目试试 非常感谢

**Comment by it-ionic** [comment]
您的手机系统是那个版本

我的是iphone5  ios9.1 升级到最新的9.3 都不行，

重新创建项目cordova 5.2  cordova 6.0测试都不行。都会有返回的时候app会退出



Other Sources 下面的main.m 有个错误

您有时间调试试试

**Comment by it-ionic** [comment]
哥实在不好意思   成功了

可能以前的支付宝版本太旧了，重新卸载支付宝然后重新安装就可以了
