### ISSUE TITLE
plugin.xml文件问题

### ISSUE THREAD

**Issue by songhaipeng** [charleyw/cordova-plugin-alipay#25]
在使用Visual Studio来添加此插件的时候，会提示plugin.xml文件存在错误，经过检查应该是在plugin节点声明的时候添加xmlns:android="http://schemas.android.com/apk/res/android"，麻烦修正一下吧。

**Comment by charleyw** [comment]
你可以提一个pull request吗，我这边没有visual studio不太好测试。

**Comment by songhaipeng** [comment]
我试试看，没有用过pull request。
我这里使用的VisualStudio 2015 + Apache for Cordova来开发的，VisualStudio有一个添加控件的工具，其他控件没有问题，但是这个无法引入，我检查了一下直接浏览plugin.xml文件，无法浏览，其实XML节点存在错误，检查之后没有发现什么问题，后来看是因为无法解析android:属性名，所以加入xmlns:android="http://schemas.android.com/apk/res/android"命名空间之后就可以了。
