### ISSUE TITLE
IOS couldn't call callback, but Android could in cordova 6.1.1

### ISSUE THREAD

**Issue by zhaomy2000** [charleyw/cordova-plugin-alipay#28]
Modify the file AppDelegate.m, add the following code, this bug will disappear.
# import <AlipaySDK/AlipaySDK.h>
- (BOOL)application:(UIApplication *)application
          openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation {
  
    if ([url.host isEqualToString:@"safepay"]) {
        //跳转支付宝钱包进行支付，处理支付结果
        [[AlipaySDK defaultService] processOrderWithPaymentResult:url standbyCallback:^(NSDictionary *resultDic) {
            NSLog(@"result = %@",resultDic);
        }];
    }
    return YES;
  }

**Comment by zhaomy2000** [comment]
If Alipay app is installed in IOS, the bug will appear. when I uninstall alipay app, the bug will disappear.

**Comment by charleyw** [comment]
Sorry for reply too later. I just tried on my iPhone 6, iOS 9.2.1. 
Seem everything is OK.

You can attach iPhone to xcode and run with it, you can see the error log if something happened.
