### ISSUE TITLE
Android和iOS的回调参数格式不一样

### ISSUE THREAD

**Issue by puny-d** [charleyw/cordova-plugin-alipay#3]
你好，我发现支付返回后iOS的回调参数和Android的回调参数的格式是不一样的，不知道这个是不是支付宝SDK导致，还是其他的？

**Comment by charleyw** [comment]
支付宝的SDK里面对iOS和android的处理不太一样。我现在只是把它返回的结果拼接了一下而已。
主要是现在没有时间，其实这个应该做成callback的形式，就能把返回结果统一了。

**Comment by charleyw** [comment]
fixed in https://github.com/charleyw/cordova-plugin-alipay/commit/db0bfb70b2ca39dd62c62a8f2f5f0dbfbf462b98
