### ISSUE TITLE
上传Appstore被拒

### ISSUE THREAD

**Issue by wewoor** [charleyw/cordova-plugin-alipay#31]
作者您好，不知道怎么联系你。我最近用这个插件上传到Appstore审核时被拒，貌似使用了非公开的API，经过我的排查，请问会不会跟这个插件有关。

> Apps that use non-public APIs will be rejected

**Comment by charleyw** [comment]
最近一个月我们自己的App提交了两次了，都过了。你确定一下是不是这个插件的问题。

最好能让他提供一下是那些API是non-public API，方便排查，修改。可以让我确定一下是不是这个插件的问题

修改：刚才又查了一下，这个月第三次提交，今天刚过审。
