### ISSUE TITLE
我集成后，得到bug：Attempt to invoke virtual method "int java.lang.String.length()" on a null object reference

### ISSUE THREAD

**Issue by ChangJeffrey** [charleyw/cordova-plugin-alipay#32]
我在plugin.xml中，分别改了ANDROID和IOS的两处partner和seller，替换成了我自己的真实的内容。
集成后，运行得到了以上错误，会是什么问题？
我的cordova是6.1.0
使用的是IONIC

**Comment by charleyw** [comment]
private key 也需要改，并且key需要PCKS格式的

这个错的原因是 因为 privatekey 没找到。或者格式错了。

**Comment by ChangJeffrey** [comment]
@charleyw 你好！
我手工安装了一次：1、下载到本地，修改plugin.xml，先删除了PRIVATE_KEY那条，改了两处privatekey
2、使用cordova plugin add $CORDOVA_PLUGIN_DIR --variable PARTNER_ID=[你的商户PID可以在账户中查询] --variable SELLER_ACCOUNT=[你的商户支付宝帐号]
3、打开 安装目标文件夹下的plugin目录下的cordova-plugin-alipay/plugin.xml，发现里面的两个值未改变，也没增加value=...等内容，仍是：
<preference name="PARTNER_ID"/>
	<preference name="SELLER_ACCOUNT"/>
/*以下省略一部分内容*/
<platform name="android">
    <config-file target="res/xml/config.xml" parent="/*">
		<preference name="partner" value="$PARTNER_ID" />
		<preference name="seller" value="$SELLER_ACCOUNT" />
<preference name="privatekey" value="MIICXAIB...." />
4、再集成，仍是这个错误。
还可能是什么错误？是否可以把这三个值直接写入到src/android/alipayplugin.java里面？

注：我在编译中也遇到了以下错误，但不影响使用，显示成功。
:compileDebugJavaWithJavac注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

**Comment by ChangJeffrey** [comment]
@charleyw 你好！
我手工安装了一次：1、下载到本地，修改plugin.xml，先删除了PRIVATE_KEY那条，改了两处privatekey
2、使用cordova plugin add $CORDOVA_PLUGIN_DIR --variable PARTNER_ID=[你的商户PID可以在账户中查询] --variable SELLER_ACCOUNT=[你的商户支付宝帐号]
3、打开 安装目标文件夹下的plugin目录下的cordova-plugin-alipay/plugin.xml，发现里面的两个值未改变，也没增加value=...等内容，仍是：
`
<preference name="PARTNER_ID"/>
	<preference name="SELLER_ACCOUNT"/>
/*以下省略一部分内容*/
<platform name="android">
    <config-file target="res/xml/config.xml" parent="/*">
		<preference name="partner" value="$PARTNER_ID" />
		<preference name="seller" value="$SELLER_ACCOUNT" />
<preference name="privatekey" value="MIICXAIB...." />
`
4、再集成，仍是这个错误。
还可能是什么错误？是否可以把这三个值直接写入到src/android/alipayplugin.java里面？

注：我在编译中也遇到了以下错误，但不影响使用，显示成功。
:compileDebugJavaWithJavac注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

**Comment by ChangJeffrey** [comment]
你好！感谢开源这个插件！！！

我查了一下，生成KEY时是PCK8.
我手工安装了一次：1、下载到本地，修改plugin.xml，先删除了PRIVATE_KEY那条，改了两处privatekey
2、使用cordova plugin add $CORDOVA_PLUGIN_DIR --variable PARTNER_ID=[你的商户PID可以在账户中查询] --variable SELLER_ACCOUNT=[你的商户支付宝帐号]
3、打开 安装目标文件夹下的plugin目录下的cordova-plugin-alipay/plugin.xml，发现里面的两个值未改变，也没增加value=...等内容，仍是：
 <preference name="PARTNER_ID"/>
<preference name="SELLER_ACCOUNT"/>
/以下省略一部分内容/
<platform name="android">
<config-file target="res/xml/config.xml" parent="/*">
<preference name="partner" value="$PARTNER_ID" />
<preference name="seller" value="$SELLER_ACCOUNT" />
<preference name="privatekey" value="MIICXAIB...." /> 
4、再集成，仍是这个错误。
还可能是什么错误？是否可以把这三个值直接写入到src/android/alipayplugin.java里面？

注：我在编译中也遇到了以下错误，但不影响使用，显示成功。
:compileDebugJavaWithJavac注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

**Comment by wangxiaochuan366** [comment]
我用过这位大神的插件，建议采用自动安装

**Comment by ChangJeffrey** [comment]
各位，我调用成功了，我把经验贡献给大家。

1、由于我老是自己消化理念，造成使用PCKS8的密码错误，以为存成文件的也是经过PCKS8处理过的。
2、重新按流程，把打到屏幕上的PCKS8密钥抄下来，去空格和回车处理后，再放入到privatekey的value中。
3、我是把两处的PARTNER_ID和SELLER_ACCOUNT都手工填写了。
4、手工安装，编译成功。

再次谢谢楼主的开源。
