### ISSUE TITLE
调用后  弹出 null

### ISSUE THREAD

**Issue by 312977** [charleyw/cordova-plugin-alipay#35]
app功能都正常 机器上也安装了支付宝，其他程序都能正确打开支付宝，
$scope.zhifu = function () {
window.alipay.pay({
tradeNo: new Date().getTime(),
subject: "测试标题",
body: "我是测试内容",
price: 0.02,
notifyUrl: "http://your.server.notify.url"
}, function (successResults) {
alert(successResults);
}, function(errorResults) {
alert(errorResults);
});
}
alert(errorResults); 我打断点 他走到这里 直接弹出 null ，请问是什么情况

**Comment by 312977** [comment]
6.0 系统手机上上弹 attemp to invoke virtual method 'int java.lang.String.length()' on a null object reference

**Comment by 312977** [comment]
谈NULL的手机是4.4

**Comment by charleyw** [comment]
检查一下private key的格式 是不是 PCKS8，详细看这个issue的内容：#26
参照这里再检查一下private key: https://github.com/charleyw/cordova-plugin-alipay#关于私钥
