### ISSUE TITLE
命令行参数的长度限制？

### ISSUE THREAD

**Issue by pluswave** [charleyw/cordova-plugin-alipay#4]
cordova 5.4.0 / ionic 1.7.8 使用命令行引入插件后 package.json 和 plugins/fetch.json 中的 $PRIVATE_KEY都正确，但是platforms中目标文件还是 $PRIVATE_KEY，需要手工修改，这是什么问题啊？ 我猜是 variable 的值不能太长，触发了cordova的相关BUG。

**Comment by charleyw** [comment]
是因为之前我把自动从命令行获取 private_key 去掉了，因为之前发现很多人都是cordova 5以下的版本。我之后会修正。

**Comment by pluswave** [comment]
@charleyw 谢谢，我也明白了，本地打了个补丁OK了。

**Comment by charleyw** [comment]
fixed in https://github.com/charleyw/cordova-plugin-alipay/commit/dfa2abdd2e56e1b79e744305ee56a110f52b53c0
