### ISSUE TITLE
请求的参数少了sign字段和sign_type.

### ISSUE THREAD

**Issue by zhougonglai** [charleyw/cordova-plugin-alipay#49]
请求样例:
<img width="694" alt="qq20160905-0 2x" src="https://cloud.githubusercontent.com/assets/10954751/18239495/422b5d66-7378-11e6-8bc4-1b2c058a6851.png">
实际请求样例:
<img width="418" alt="qq20160905-1 2x" src="https://cloud.githubusercontent.com/assets/10954751/18239520/66b44f80-7378-11e6-8f13-e9b58e4914cf.png">
目前返回的一直是6001,想知道如何解决这个问题？

**Comment by charleyw** [comment]
那个打印出内容 确实是不包括的type和sign_type的，所以没显示是正常的。
6001有可能是支付宝后台配置的问题。
你可以去支付宝下载一下官方的例子，把你的这些参数填进去试试，确认支付宝的配置没错

**Comment by JiuYun** [comment]
这个sign 目前是rsa的能改成md5的么？
