### ISSUE TITLE
提示 private key is NULL 怎么回事呀

### ISSUE THREAD

**Issue by zzlsucceed** [charleyw/cordova-plugin-alipay#5]
privatekey 也打印出来了 是存在的，执行到这个代码的时候 就报错了
id<DataSigner> signer = CreateRSADataSigner(self.privateKey);
NSString *signedString = [signer signString:orderSpec];
求解惑

**Comment by zzlsucceed** [comment]
已解决！  私钥使用 PKCS8格式 即可

**Comment by charleyw** [comment]
嗯，我都是按照官方文档走的，官方文档提示用PKCS8格式。

**Comment by zzlsucceed** [comment]
弱弱地问下 你这个调用之后的 成功失败回调 在哪里写啊

**Comment by zzlsucceed** [comment]
还有就是fromUrlScheme这个参数我没写 影响那个notifyUrl么 好像没有通知到我的这个页面

**Comment by charleyw** [comment]
这个没有加callback. 所以没有成功失败的callback...

获取成功失败是通过fromUrlScheme完成的。

**Comment by charleyw** [comment]
比如我自己的app里面，有一个支付完成的界面。这个fromUrlScheme就是指向这个页面的。

**Comment by zzlsucceed** [comment]
good 了解了

**Comment by zzlsucceed** [comment]
我的程序是 SenchaTouch写的单页面程序- -  这个 URL Scheme 咋整- -

**Comment by charleyw** [comment]
你的APP设置了URL Scheme么？ 看看这个：https://github.com/EddyVerbruggen/Custom-URL-scheme

**Comment by charleyw** [comment]
刚才大体看了一下SenchaTouch，好吧，感觉还挺复杂的。

我说一下那个fromUrlScheme是怎么工作的吧：
1. 支付完成的页面叫A，你可以通过某个url访问，比如说，`woshischeme://apage`
   这里`woshischeme`就是前面说的URL Scheme，作用你可以理解为就是代表你的APP，后面跟的`//apage`就是代表A页面的路径
2. 支付成功支付宝会调用`woshischeme://apage`，意思就是打开`woshischeme`代表的APP（`woshischeme`和APP的映射是系统做的），并且到`apage`这个页面（`apage`和A页面的映射**是需要你自己做的**，也就是俗称的路由 [SenchaTouch的路由](http://docs.sencha.com/touch/2.4/core_concepts/history_support.html)）。

所以呢，用这个插件的基本点，1. 你使用URL Scheme 2. 你有路由或者其他东西能表示页面的状态

后面等有时间，我再把callback加上

**Comment by zzlsucceed** [comment]
好！

**Comment by charleyw** [comment]
fixed in https://github.com/charleyw/cordova-plugin-alipay/commit/db0bfb70b2ca39dd62c62a8f2f5f0dbfbf462b98
