### ISSUE TITLE
回调参数少了流水号

### ISSUE THREAD

**Issue by iyibo** [charleyw/cordova-plugin-alipay#50]
@charleyw  你好，我在ios平台成功调用了你的插件并且成功回调了参数successResults，但是里面少了trade_no流水号，请问是notify_url的问题还是其他什么原因

**Comment by iyibo** [comment]
后来通过服务器的回调拿到了流水号，之前服务器代码错了

**Comment by charleyw** [comment]
对的，因为所有核心的交易信息应该是在后台处理的。
