### ISSUE TITLE
支付时是重新打开支付宝APP

### ISSUE THREAD

**Issue by childpan** [charleyw/cordova-plugin-alipay#51]
安卓是会在我的APP项目内弹出支付框，为什么ios是跳出APP项目，打开支付宝APP，是我哪边设置 不对吗

**Comment by charleyw** [comment]
这个好像跟不同系统不太一样，iOS应该是没有办法在App内打开支付宝的，所以会打开支付宝App。

还有，如果机器上没有装支付宝的话，会在App内打开网页版本的支付宝进行支付。
