### ISSUE TITLE
咨询一下这里安装时的PRIVATE_KEY

### ISSUE THREAD

**Issue by junhui75165** [charleyw/cordova-plugin-alipay#57]
rsa_private_key.pem（RSA私钥）、rsa_private_key_pkcs8.pem（pkcs8格式RSA私钥）和rsa_public_key.pem（对应RSA公钥）3个文件，这里用到的PRIVATE_KEY是值得哪一个0.0

**Comment by charleyw** [comment]
rsa_private_key_pkcs8.pem
用的是这个文件的文件内容，除去首尾行
