### ISSUE TITLE
有空做个回调方法呗。。

### ISSUE THREAD

**Issue by zzlsucceed** [charleyw/cordova-plugin-alipay#7]
android ios两个平台返回消息不太一样，而且 有支付宝客户端的跟没有支付宝客户端的返回机制好像也不太一样。。 感觉好难处理啊 ，觉得如果插件调用有成功失败回调就好多了，就不用处理那么多情况了，求添加带信息的回调

**Comment by zzlsucceed** [comment]
话说那个 IOS平台上的 H5收银台 返回消息 我怎么接收

**Comment by zzlsucceed** [comment]
回调已自行处理完毕~

**Comment by charleyw** [comment]
棒棒的

**Comment by charleyw** [comment]
fixed in https://github.com/charleyw/cordova-plugin-alipay/commit/db0bfb70b2ca39dd62c62a8f2f5f0dbfbf462b98
