### ISSUE TITLE
android调用没反应

### ISSUE THREAD

**Issue by mjbin** [charleyw/cordova-plugin-alipay#9]
你好，我按照你的文档安装，有几点不是很明白，

1.我现在用的是这种方法安装的，cordova版本5.4.1，应该没问题吧
cordova plugin add $CORDOVA_PLUGIN_DIR --variable PARTNER_ID=[你的商户PID可以在账户中查询] --variable SELLER_ACCOUNT=[你的商户支付宝帐号] --variable PRIVATE_KEY=[你生成的private key]
2.你的调用方法是用的window全局调用吗？我用angular调用的话是这么写的
![image](https://cloud.githubusercontent.com/assets/3965629/12001751/444f37c8-ab2a-11e5-843a-9f35dbcbaf56.png)
能弹出123456，但是在调用的时候报错了，显示pay not define;不知懂这里应该怎么调用pay函数

3.我支付宝那边应该用还没通过审核，不知道会不会影响插件的使用

**Comment by charleyw** [comment]
1. --variable PRIVATE_KEY最近有Bug，最近没时间修，所以我把自动添加PRIVATE_KEY去掉了，所以你需要去plugin.xml里面手动修改PRIVATE_KEY
2. alipay是绑定到window命名空间上的，所以应该是全局的。我没用过angular，所以不是很确定为什么会报 pay not define。但是 ，你这里有一个错误：tradeNo应该是一个值，你貌似没有定义tradeNo。
3. 没过审核的话，应该会弹不出支付宝页面。

**Comment by mjbin** [comment]
感谢回复，一二点已经修改，剩下的等审核之后再试试。
